### ISSUE TITLE
Having issue with reading HTTP headers for rate-limit

### ISSUE THREAD

**Issue by henrytseng** [lob/lob-ruby#137]
Using the API call `@lob.letters.create`.  Letter gets successfully sent out but not getting HTTP headers for rate-limit

```
@lob.letters.create(
  description: "Demo Letter",
  to: {
    name: "Harry Zhang",
    address_line1: "123 Test Street",
    address_city: "Mountain View",
    address_state: "CA",
    address_country: "US",
    address_zip: "94041"
  },
  from: {
    name: "Ami Wang",
    address_line1: "123 Test Street",
    address_city: "Mountain View",
    address_state: "CA",
    address_country: "US",
    address_zip: "94041"
  },
  file: "<html style='padding-top: 3in; margin: .5in;'>HTML Letter for {{name}}</html>",
  data: {
    name: "Harry"
  },
  color: true
)
```

**Comment by mgartner** [comment]
Hey Henry, thanks for reaching out.

Currently we do not make HTTP headers available in this client. It's something we've been asked to add before. I'll discuss with the team and figure out how we can address this for you.

**Comment by bkubic** [comment]
@mgartner This is a huge gap - how are we supposed to know how to rate limit requests if the info isn't provided? Guess?

**Comment by mgartner** [comment]
@henrytseng @bkubic Thanks for the feedback. We've added support to access the entire RestClient Response object, including the headers.

Please use the latest version of the gem and checkout the README for how to access the headers.

https://rubygems.org/gems/lob/versions/2.5.0
