### ISSUE TITLE
It is impossible to serialize response returned by Lob

### ISSUE THREAD

**Issue by abezzub-upstart** [lob/lob-ruby#142]
Following code adds additional method on a Hash that is returned by Lob:
https://github.com/lob/lob-ruby/blob/master/lib/lob.rb#L42-L44

If I try to save that hash in a serialized encrypted column in DB I get following error:
```
TypeError: singleton can't be dumped
	from /app/vendor/bundle/ruby/2.3.0/gems/attr_encrypted-3.0.1/lib/attr_encrypted.rb:258:in `dump'
	from /app/vendor/bundle/ruby/2.3.0/gems/attr_encrypted-3.0.1/lib/attr_encrypted.rb:258:in `encrypt'
	from /app/vendor/bundle/ruby/2.3.0/gems/attr_encrypted-3.0.1/lib/attr_encrypted.rb:337:in `encrypt'
	from /app/vendor/bundle/ruby/2.3.0/gems/attr_encrypted-3.0.1/lib/attr_encrypted.rb:159:in `block (2 levels) in attr_encrypted'
```

Is it possible to remove the code that adds a method on the fly to the Hash?

**Comment by mgartner** [comment]
We'd like to remain adding the singleton method to the response hash, because it allows access to additional information like response headers.

If you are storing the response as JSON, can you try converting the hash to JSON first with `.to_json`. The resulting JSON should only include the response body and not the singleton method.

**Comment by abezzub-upstart** [comment]
The problem with current implementation is it is completely non-obvious that Lob returns a non-standard hash and I wasted some time trying to understand what is going on. Maybe you can define a PORO class with 2 methods returning a hash and JSON instead of adding an extra method on a Hash? This way it is clear for the user of the API what is returned and how it can be used.

**Comment by mgartner** [comment]
That makes sense. Thanks for the suggestion. Doing this would require a major version increment because it would be a breaking change. We'll keep this in mind for future release.

Thanks again.
