### ISSUE TITLE
require 'lob' does not work

### ISSUE THREAD

**Issue by siannopollo** [lob/lob-ruby#207]
The documentation states that to get started one need only run:
```
gem install 'lob'
require 'lob'
```

This no longer seems to work after the 6.0.0 release, as there is no longer a `lib/lob.rb` file to require. I'm using rails 5.2.8.1, ruby 2.6.5p114 and trying to load lob looks something like this:
```
$ rails c
Loading development environment (Rails 5.2.8.1)
2.6.5 :001 > require 'lob'
Traceback (most recent call last):
        1: from (irb):1
LoadError (cannot load such file -- lob)
2.6.5 :002 > Lob
Traceback (most recent call last):
        2: from (irb):2
        1: from (irb):2:in `rescue in irb_binding'
NameError (uninitialized constant Lob)
2.6.5 :003 > require 'openapi_client'
 => true 
2.6.5 :004 > Lob
```

This could probably be solved by adding lib/lob.rb back to the project and making that `require 'openapi_client'`.

**Comment by BennyKitchell** [comment]
Hey @siannopollo 

Great catch on this, I will get your PR merged and get a new release out by EoD. Thanks!
