### ISSUE TITLE
Various warnings when running tests and loading library

### ISSUE THREAD

**Issue by siannopollo** [lob/lob-ruby#209]
When I was running the tests for my last pull request I noticed a lot of warnings on my version of ruby. Most of them were along the lines of RegExp errors like:
```
lob-ruby/lib/openapi_client/models/thumbnail.rb:88: warning: character class has '-' without escape
```

Also saw one generated by the tests:
```
lob-ruby/__tests__/Api/Address.unit.rb:156: warning: already initialized constant DATE_FILTER
lob-ruby/__tests__/Api/BankAccount.unit.rb:158: warning: previous definition of DATE_FILTER was here
```

I should be able to clear up both and will submit a pull request. Since they're warnings and not really errors I can't think of any good tests to show them being fixed other than just fixing them. If you have any ideas of a way to test these (ie: a way to capture warnings in ruby and ensure they don't show up after the fix is applied), please let me know.

**Comment by siannopollo** [comment]
Any word on this issue?

**Comment by siannopollo** [comment]
Bumping this again. Is the lack of movement on this caused by a problem in the pull request? If you want to see something different just let me know and I can take another crack at it.

**Comment by broksonic21** [comment]
confirming we see this as well, would love this resolved.

**Comment by BennyKitchell** [comment]
@broksonic21  @siannopollo  New version with that change merged can be found [here](https://rubygems.org/gems/lob/versions/6.0.2). Thank you for being patient with us!

**Comment by broksonic21** [comment]
I filed https://github.com/lob/lob-ruby/issues/220 as this seems to have regressed in 6.0.3. Thanks for consideration!
