### ISSUE TITLE
RestClient::UnprocessableEntity: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by ankurp** [lob/lob-ruby#22]
I am trying to create a postcard with front and back pdf that are locally generated. The files looks correct and here is the code.

```
  @lob = Lob()
  opts = {
    name: name,
    to: location_to
    from: location_from,
    front: File.new(front_path),
    back: File.new(back_path),
    full_bleed: 0
  }
  @lob.postcards.create(opts)
```

After debugging I see that the error is happening in this file at line lob.rb 
`JSON(RestClient.send(method, url, parameters))`

The error response I get is below. Because there is a rescue around that method block this error is swallowed up and an Lob generic error message is shown:
`RestClient::UnprocessableEntity: 422 Unprocessable Entity`
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in`process_result'
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    from /Users/ankur/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:853:in`start'
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in`execute'
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/rest-client-1.6.7/lib/restclient.rb:72:in`post'
    from (irb):19:in `submit'
    from /Users/ankur/.rvm/gems/ruby-2.1.1/gems/lob-1.2/lib/lob/v1/postcard.rb:26:in`create'
    from .../app/models/message.rb:125:in `deliver'

Has anyone encountered this and know how to solve this. I am following the documentation to the spec and my code use to work. I am using the latest 1.2 version of the Gem with 1.6.7 version of rest-client

**Comment by batshoes** [comment]
There's also a typo on line 4. There should be a comma at the end to signify next key-value pair.
Not that it's important two years after the fact.
