### ISSUE TITLE
Lob 6.0.3: Various warnings when running tests and loading library

### ISSUE THREAD

**Issue by broksonic21** [lob/lob-ruby#220]
Lob 6.0.2 fixed a bunch of warnings, but these appear back in Lob 6.0.3:

```
warning: character class has '-' without escape
```

https://github.com/lob/lob-ruby/issues/209 has more info on the original fix.

You can see the regression here, amongst other lines:
https://github.com/lob/lob-ruby/compare/v6.0.2...v6.0.3#diff-394b2cc6b345c7ebd5c1693dcd21d403a6c17b95200e382fe646878a708ce963R260 

At minimum, I am seeing it here in our app:

```
        DEPRECATION WARNING: /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/lob-6.0.3/lib/openapi_client/models/thumbnail.rb:118: warning: character class has '-' without escape
   
        DEPRECATION WARNING: /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/lob-6.0.3/lib/openapi_client/models/thumbnail.rb:129: warning: character class has '-' without escape
   
        DEPRECATION WARNING: /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/lob-6.0.3/lib/openapi_client/models/thumbnail.rb:140: warning: character class has '-' without escape
   
        DEPRECATION WARNING: /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/lob-6.0.3/lib/openapi_client/models/letter.rb:498: warning: character class has '-' without escape
```

**Comment by broksonic21** [comment]
fyi @siddharthpant92 (as author of 6.0.3) and @BennyKitchell  (as maintainer on 6.0.2 fix)

**Comment by siddharthpant92** [comment]
Hey @broksonic21 Thank you for bringing this up. Hopefully his has been fixed in https://github.com/lob/lob-ruby/pull/221. 
I can close this issue out once you confirm or if we don't hear from you soon. 
Sorry for having those warnings re-surface

**Comment by broksonic21** [comment]
Yep, this worked for us - thanks!
